USE ROLE ACCOUNTADMIN;

-- Roles
SET MY_USER = CURRENT_USER();
CREATE OR REPLACE ROLE BIG_ROLE;
GRANT ROLE BIG_ROLE TO ROLE SYSADMIN;
GRANT ROLE BIG_ROLE TO USER IDENTIFIER($MY_USER);

GRANT EXECUTE TASK ON ACCOUNT TO ROLE BIG_ROLE;
GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE BIG_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE BIG_ROLE;

-- Databases
CREATE OR REPLACE DATABASE BIG_DB;
GRANT IMPORTED PRIVILEGES ON DATABASE US_HOUSING__REAL_ESTATE_ESSENTIALS TO ROLE BIG_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE US_POINTS_OF_INTEREST__ADDRESSES TO ROLE BIG_ROLE;

GRANT OWNERSHIP ON DATABASE BIG_DB TO ROLE BIG_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE FINANCIAL__ECONOMIC_ESSENTIALS TO ROLE BIG_ROLE;


GRANT IMPORTED PRIVILEGES ON DATABASE CRIME_STATISTICS TO ROLE BIG_ROLE;

-- Warehouses
CREATE OR REPLACE WAREHOUSE BIG_WH WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 300, AUTO_RESUME= TRUE;
GRANT OWNERSHIP ON WAREHOUSE BIG_WH TO ROLE BIG_ROLE;


-- ----------------------------------------------------------------------------
-- Step #3: Create the database level objects
-- ----------------------------------------------------------------------------
--USE ROLE BIG_ROLE;
USE WAREHOUSE BIG_WH;
USE DATABASE BIG_DB;

USE ROLE BIG_ROLE;


-- Schemas

CREATE OR REPLACE SCHEMA HARMONIZED;

CREATE OR REPLACE SCHEMA ANALYTICS;